/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface RouterOldInterface extends ethers.utils.Interface {
  functions: {
    "REVISION()": FunctionFragment;
    "WETH()": FunctionFragment;
    "calculateBalance(address,address,address,uint256)": FunctionFragment;
    "calculateOpenPosition(address,address,uint256,uint256)": FunctionFragment;
    "calculateOpenProxyPosition(address,address,address,uint256,uint256)": FunctionFragment;
    "calculateOpenProxyShortPosition(address,address,address,uint256,uint256)": FunctionFragment;
    "calculateOpenShortPosition(address,address,uint256,uint256)": FunctionFragment;
    "calculateProxyBalance(address,address,address,address,uint256)": FunctionFragment;
    "calculateProxyShortBalance(address,address,address,address,uint256)": FunctionFragment;
    "calculateShortBalance(address,address,address,uint256)": FunctionFragment;
    "closePosition(uint256,uint256,address,address,address,uint256)": FunctionFragment;
    "closePositionETH(uint256,uint256,address,address,uint256)": FunctionFragment;
    "closePositionETHWithReferrer(uint256,uint256,address,address,uint256,address)": FunctionFragment;
    "closePositionWithReferrer(uint256,uint256,address,address,address,uint256,address)": FunctionFragment;
    "closeProxyPosition(uint256,uint256,address,address,address,address,uint256)": FunctionFragment;
    "closeProxyPositionETH(uint256,uint256,address,address,address,uint256)": FunctionFragment;
    "closeProxyPositionETHWithReferrer(uint256,uint256,address,address,address,uint256,address)": FunctionFragment;
    "closeProxyPositionWithReferrer(uint256,uint256,address,address,address,address,uint256,address)": FunctionFragment;
    "closeProxyShortPosition(uint256,uint256,address,address,address,address,uint256)": FunctionFragment;
    "closeProxyShortPositionWithReferrer(uint256,uint256,address,address,address,address,uint256,address)": FunctionFragment;
    "closeShortPosition(uint256,uint256,address,address,address,uint256)": FunctionFragment;
    "closeShortPositionWithReferrer(uint256,uint256,address,address,address,uint256,address)": FunctionFragment;
    "deposit(address,uint256,address)": FunctionFragment;
    "depositETH(address)": FunctionFragment;
    "depositShortable(address,uint256,address)": FunctionFragment;
    "fill(address,uint256)": FunctionFragment;
    "getPosition(address,address,address)": FunctionFragment;
    "getProxyPosition(address,address,address,address)": FunctionFragment;
    "getProxyShortPosition(address,address,address,address)": FunctionFragment;
    "getShortPosition(address,address,address)": FunctionFragment;
    "incentivize(address,uint256)": FunctionFragment;
    "initialize(address,address,address,address,address,address)": FunctionFragment;
    "openPosition(uint256,uint256,uint256,address,address,address,uint256)": FunctionFragment;
    "openPositionETH(uint256,uint256,address,address,uint256)": FunctionFragment;
    "openPositionETHWithReferrer(uint256,uint256,address,address,uint256,address)": FunctionFragment;
    "openPositionWithReferrer(uint256,uint256,uint256,address,address,address,uint256,address)": FunctionFragment;
    "openProxyPosition(uint256,uint256,uint256,address,address,address,address,uint256)": FunctionFragment;
    "openProxyPositionETH(uint256,uint256,address,address,address,uint256)": FunctionFragment;
    "openProxyPositionETHWithReferrer(uint256,uint256,address,address,address,uint256,address)": FunctionFragment;
    "openProxyPositionWithReferrer(uint256,uint256,uint256,address,address,address,address,uint256,address)": FunctionFragment;
    "openProxyShortPosition(uint256,uint256,uint256,address,address,address,address,uint256)": FunctionFragment;
    "openProxyShortPositionWithReferrer(uint256,uint256,uint256,address,address,address,address,uint256,address)": FunctionFragment;
    "openShortPosition(uint256,uint256,uint256,address,address,address,uint256)": FunctionFragment;
    "openShortPositionWithReferrer(uint256,uint256,uint256,address,address,address,uint256,address)": FunctionFragment;
    "pairFactory()": FunctionFragment;
    "reserveFactory()": FunctionFragment;
    "stake(address,uint256,uint16,address)": FunctionFragment;
    "swapFactory()": FunctionFragment;
    "swapRouter()": FunctionFragment;
    "sweepReserveFee(address)": FunctionFragment;
    "sweepShortingReserveFee(address)": FunctionFragment;
    "unstake(address,address)": FunctionFragment;
    "withdraw(address,uint256,address)": FunctionFragment;
    "withdrawETH(uint256,address)": FunctionFragment;
    "withdrawShortable(address,uint256,address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "REVISION", values?: undefined): string;
  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "calculateBalance",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateOpenPosition",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateOpenProxyPosition",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateOpenProxyShortPosition",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateOpenShortPosition",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateProxyBalance",
    values: [string, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateProxyShortBalance",
    values: [string, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateShortBalance",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closePosition",
    values: [BigNumberish, BigNumberish, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closePositionETH",
    values: [BigNumberish, BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closePositionETHWithReferrer",
    values: [BigNumberish, BigNumberish, string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "closePositionWithReferrer",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "closeProxyPosition",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "closeProxyPositionETH",
    values: [BigNumberish, BigNumberish, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeProxyPositionETHWithReferrer",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "closeProxyPositionWithReferrer",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      string,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "closeProxyShortPosition",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "closeProxyShortPositionWithReferrer",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      string,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "closeShortPosition",
    values: [BigNumberish, BigNumberish, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeShortPositionWithReferrer",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "depositETH", values: [string]): string;
  encodeFunctionData(
    functionFragment: "depositShortable",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "fill",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getProxyPosition",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getProxyShortPosition",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getShortPosition",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "incentivize",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "openPosition",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "openPositionETH",
    values: [BigNumberish, BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "openPositionETHWithReferrer",
    values: [BigNumberish, BigNumberish, string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "openPositionWithReferrer",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "openProxyPosition",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "openProxyPositionETH",
    values: [BigNumberish, BigNumberish, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "openProxyPositionETHWithReferrer",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "openProxyPositionWithReferrer",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      string,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "openProxyShortPosition",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "openProxyShortPositionWithReferrer",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      string,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "openShortPosition",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "openShortPositionWithReferrer",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "pairFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "swapFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sweepReserveFee",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "sweepShortingReserveFee",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawETH",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawShortable",
    values: [string, BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "REVISION", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateOpenPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateOpenProxyPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateOpenProxyShortPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateOpenShortPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateProxyBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateProxyShortBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateShortBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closePositionETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closePositionETHWithReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closePositionWithReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeProxyPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeProxyPositionETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeProxyPositionETHWithReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeProxyPositionWithReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeProxyShortPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeProxyShortPositionWithReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeShortPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeShortPositionWithReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "depositETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositShortable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fill", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProxyPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProxyShortPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShortPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incentivize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "openPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openPositionETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openPositionETHWithReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openPositionWithReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openProxyPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openProxyPositionETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openProxyPositionETHWithReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openProxyPositionWithReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openProxyShortPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openProxyShortPositionWithReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openShortPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openShortPositionWithReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pairFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sweepReserveFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sweepShortingReserveFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawShortable",
    data: BytesLike
  ): Result;

  events: {};
}

export class RouterOld extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: RouterOldInterface;

  functions: {
    REVISION(overrides?: CallOverrides): Promise<[BigNumber]>;

    WETH(overrides?: CallOverrides): Promise<[string]>;

    calculateBalance(
      lendable: string,
      tradable: string,
      trader: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        amountOut: BigNumber;
        profit: BigNumber;
        debtPayable: BigNumber;
        protocolFee: BigNumber;
      }
    >;

    calculateOpenPosition(
      lendable: string,
      tradable: string,
      amount: BigNumberish,
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        maxAmountIn: BigNumber;
        borrowAmount: BigNumber;
        borrowRate: BigNumber;
        liquidationCost: BigNumber;
      }
    >;

    calculateOpenProxyPosition(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      amount: BigNumberish,
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        maxAmountIn: BigNumber;
        borrowAmount: BigNumber;
        borrowRate: BigNumber;
        liquidationCost: BigNumber;
      }
    >;

    calculateOpenProxyShortPosition(
      lendable: string,
      proxyLendable: string,
      shortable: string,
      amount: BigNumberish,
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        maxAmountIn: BigNumber;
        borrowAmount: BigNumber;
        borrowRate: BigNumber;
        liquidationCost: BigNumber;
      }
    >;

    calculateOpenShortPosition(
      lendable: string,
      shortable: string,
      amount: BigNumberish,
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        maxAmountIn: BigNumber;
        borrowAmount: BigNumber;
        borrowRate: BigNumber;
        liquidationCost: BigNumber;
      }
    >;

    calculateProxyBalance(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        amountOut: BigNumber;
        profit: BigNumber;
        debtPayable: BigNumber;
        protocolFee: BigNumber;
      }
    >;

    calculateProxyShortBalance(
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        amountOut: BigNumber;
        profit: BigNumber;
        debtPayable: BigNumber;
        protocolFee: BigNumber;
      }
    >;

    calculateShortBalance(
      lendable: string,
      shortable: string,
      trader: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        amountOut: BigNumber;
        profit: BigNumber;
        debtPayable: BigNumber;
        protocolFee: BigNumber;
      }
    >;

    closePosition(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    closePositionETH(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    closePositionETHWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    closePositionWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    closeProxyPosition(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    closeProxyPositionETH(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    closeProxyPositionETHWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    closeProxyPositionWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    closeProxyShortPosition(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    closeProxyShortPositionWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    closeShortPosition(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    closeShortPositionWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deposit(
      lendable: string,
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositETH(
      to: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositShortable(
      shortable: string,
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    fill(
      lendable: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getPosition(
      trader: string,
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          amount: BigNumber;
          value: BigNumber;
          selfValue: BigNumber;
          principalDebt: BigNumber;
          currentDebt: BigNumber;
          rate: BigNumber;
          currentCost: BigNumber;
          liquidationCost: BigNumber;
        }
      ] & {
        position: [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          amount: BigNumber;
          value: BigNumber;
          selfValue: BigNumber;
          principalDebt: BigNumber;
          currentDebt: BigNumber;
          rate: BigNumber;
          currentCost: BigNumber;
          liquidationCost: BigNumber;
        };
      }
    >;

    getProxyPosition(
      trader: string,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          amount: BigNumber;
          value: BigNumber;
          selfValue: BigNumber;
          principalDebt: BigNumber;
          currentDebt: BigNumber;
          rate: BigNumber;
          currentCost: BigNumber;
          liquidationCost: BigNumber;
        }
      ] & {
        position: [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          amount: BigNumber;
          value: BigNumber;
          selfValue: BigNumber;
          principalDebt: BigNumber;
          currentDebt: BigNumber;
          rate: BigNumber;
          currentCost: BigNumber;
          liquidationCost: BigNumber;
        };
      }
    >;

    getProxyShortPosition(
      trader: string,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          amount: BigNumber;
          value: BigNumber;
          selfValue: BigNumber;
          principalDebt: BigNumber;
          currentDebt: BigNumber;
          rate: BigNumber;
          currentCost: BigNumber;
          liquidationCost: BigNumber;
        }
      ] & {
        position: [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          amount: BigNumber;
          value: BigNumber;
          selfValue: BigNumber;
          principalDebt: BigNumber;
          currentDebt: BigNumber;
          rate: BigNumber;
          currentCost: BigNumber;
          liquidationCost: BigNumber;
        };
      }
    >;

    getShortPosition(
      trader: string,
      lendable: string,
      shortable: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          amount: BigNumber;
          value: BigNumber;
          selfValue: BigNumber;
          principalDebt: BigNumber;
          currentDebt: BigNumber;
          rate: BigNumber;
          currentCost: BigNumber;
          liquidationCost: BigNumber;
        }
      ] & {
        position: [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          amount: BigNumber;
          value: BigNumber;
          selfValue: BigNumber;
          principalDebt: BigNumber;
          currentDebt: BigNumber;
          rate: BigNumber;
          currentCost: BigNumber;
          liquidationCost: BigNumber;
        };
      }
    >;

    incentivize(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialize(
      _reserveFactory: string,
      _pairFactory: string,
      _swapRouter: string,
      _WETH: string,
      _xWOW: string,
      _referralProgram: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openPosition(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openPositionETH(
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openPositionETHWithReferrer(
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openPositionWithReferrer(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openProxyPosition(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openProxyPositionETH(
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openProxyPositionETHWithReferrer(
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openProxyPositionWithReferrer(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openProxyShortPosition(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openProxyShortPositionWithReferrer(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openShortPosition(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openShortPositionWithReferrer(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pairFactory(overrides?: CallOverrides): Promise<[string]>;

    reserveFactory(overrides?: CallOverrides): Promise<[string]>;

    stake(
      token: string,
      amount: BigNumberish,
      period: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapFactory(overrides?: CallOverrides): Promise<[string]>;

    swapRouter(overrides?: CallOverrides): Promise<[string]>;

    sweepReserveFee(
      lendable: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sweepShortingReserveFee(
      shortable: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unstake(
      token: string,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      lendable: string,
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawETH(
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawShortable(
      shortable: string,
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  REVISION(overrides?: CallOverrides): Promise<BigNumber>;

  WETH(overrides?: CallOverrides): Promise<string>;

  calculateBalance(
    lendable: string,
    tradable: string,
    trader: string,
    amountIn: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      amountOut: BigNumber;
      profit: BigNumber;
      debtPayable: BigNumber;
      protocolFee: BigNumber;
    }
  >;

  calculateOpenPosition(
    lendable: string,
    tradable: string,
    amount: BigNumberish,
    leverageFactor: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      maxAmountIn: BigNumber;
      borrowAmount: BigNumber;
      borrowRate: BigNumber;
      liquidationCost: BigNumber;
    }
  >;

  calculateOpenProxyPosition(
    lendable: string,
    proxyLendable: string,
    tradable: string,
    amount: BigNumberish,
    leverageFactor: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      maxAmountIn: BigNumber;
      borrowAmount: BigNumber;
      borrowRate: BigNumber;
      liquidationCost: BigNumber;
    }
  >;

  calculateOpenProxyShortPosition(
    lendable: string,
    proxyLendable: string,
    shortable: string,
    amount: BigNumberish,
    leverageFactor: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      maxAmountIn: BigNumber;
      borrowAmount: BigNumber;
      borrowRate: BigNumber;
      liquidationCost: BigNumber;
    }
  >;

  calculateOpenShortPosition(
    lendable: string,
    shortable: string,
    amount: BigNumberish,
    leverageFactor: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      maxAmountIn: BigNumber;
      borrowAmount: BigNumber;
      borrowRate: BigNumber;
      liquidationCost: BigNumber;
    }
  >;

  calculateProxyBalance(
    lendable: string,
    proxyLendable: string,
    tradable: string,
    trader: string,
    amountIn: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      amountOut: BigNumber;
      profit: BigNumber;
      debtPayable: BigNumber;
      protocolFee: BigNumber;
    }
  >;

  calculateProxyShortBalance(
    lendable: string,
    proxyLendable: string,
    shortable: string,
    trader: string,
    amountIn: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      amountOut: BigNumber;
      profit: BigNumber;
      debtPayable: BigNumber;
      protocolFee: BigNumber;
    }
  >;

  calculateShortBalance(
    lendable: string,
    shortable: string,
    trader: string,
    amountIn: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      amountOut: BigNumber;
      profit: BigNumber;
      debtPayable: BigNumber;
      protocolFee: BigNumber;
    }
  >;

  closePosition(
    amountIn: BigNumberish,
    amountOutMin: BigNumberish,
    lendable: string,
    tradable: string,
    trader: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  closePositionETH(
    amountIn: BigNumberish,
    amountOutMin: BigNumberish,
    tradable: string,
    trader: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  closePositionETHWithReferrer(
    amountIn: BigNumberish,
    amountOutMin: BigNumberish,
    tradable: string,
    trader: string,
    deadline: BigNumberish,
    referrer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  closePositionWithReferrer(
    amountIn: BigNumberish,
    amountOutMin: BigNumberish,
    lendable: string,
    tradable: string,
    trader: string,
    deadline: BigNumberish,
    referrer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  closeProxyPosition(
    amountIn: BigNumberish,
    amountOutMin: BigNumberish,
    lendable: string,
    proxyLendable: string,
    tradable: string,
    trader: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  closeProxyPositionETH(
    amountIn: BigNumberish,
    amountOutMin: BigNumberish,
    proxyLendable: string,
    tradable: string,
    trader: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  closeProxyPositionETHWithReferrer(
    amountIn: BigNumberish,
    amountOutMin: BigNumberish,
    proxyLendable: string,
    tradable: string,
    trader: string,
    deadline: BigNumberish,
    referrer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  closeProxyPositionWithReferrer(
    amountIn: BigNumberish,
    amountOutMin: BigNumberish,
    lendable: string,
    proxyLendable: string,
    tradable: string,
    trader: string,
    deadline: BigNumberish,
    referrer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  closeProxyShortPosition(
    amountIn: BigNumberish,
    amountOutMin: BigNumberish,
    lendable: string,
    proxyLendable: string,
    shortable: string,
    trader: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  closeProxyShortPositionWithReferrer(
    amountIn: BigNumberish,
    amountOutMin: BigNumberish,
    lendable: string,
    proxyLendable: string,
    shortable: string,
    trader: string,
    deadline: BigNumberish,
    referrer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  closeShortPosition(
    amountIn: BigNumberish,
    amountOutMin: BigNumberish,
    lendable: string,
    shortable: string,
    trader: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  closeShortPositionWithReferrer(
    amountIn: BigNumberish,
    amountOutMin: BigNumberish,
    lendable: string,
    shortable: string,
    trader: string,
    deadline: BigNumberish,
    referrer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deposit(
    lendable: string,
    amount: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositETH(
    to: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositShortable(
    shortable: string,
    amount: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  fill(
    lendable: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getPosition(
    trader: string,
    lendable: string,
    tradable: string,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      amount: BigNumber;
      value: BigNumber;
      selfValue: BigNumber;
      principalDebt: BigNumber;
      currentDebt: BigNumber;
      rate: BigNumber;
      currentCost: BigNumber;
      liquidationCost: BigNumber;
    }
  >;

  getProxyPosition(
    trader: string,
    lendable: string,
    proxyLendable: string,
    tradable: string,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      amount: BigNumber;
      value: BigNumber;
      selfValue: BigNumber;
      principalDebt: BigNumber;
      currentDebt: BigNumber;
      rate: BigNumber;
      currentCost: BigNumber;
      liquidationCost: BigNumber;
    }
  >;

  getProxyShortPosition(
    trader: string,
    lendable: string,
    proxyLendable: string,
    shortable: string,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      amount: BigNumber;
      value: BigNumber;
      selfValue: BigNumber;
      principalDebt: BigNumber;
      currentDebt: BigNumber;
      rate: BigNumber;
      currentCost: BigNumber;
      liquidationCost: BigNumber;
    }
  >;

  getShortPosition(
    trader: string,
    lendable: string,
    shortable: string,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      amount: BigNumber;
      value: BigNumber;
      selfValue: BigNumber;
      principalDebt: BigNumber;
      currentDebt: BigNumber;
      rate: BigNumber;
      currentCost: BigNumber;
      liquidationCost: BigNumber;
    }
  >;

  incentivize(
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialize(
    _reserveFactory: string,
    _pairFactory: string,
    _swapRouter: string,
    _WETH: string,
    _xWOW: string,
    _referralProgram: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openPosition(
    amountIn: BigNumberish,
    leverageFactor: BigNumberish,
    amountOutMin: BigNumberish,
    lendable: string,
    tradable: string,
    trader: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openPositionETH(
    leverageFactor: BigNumberish,
    amountOutMin: BigNumberish,
    tradable: string,
    trader: string,
    deadline: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openPositionETHWithReferrer(
    leverageFactor: BigNumberish,
    amountOutMin: BigNumberish,
    tradable: string,
    trader: string,
    deadline: BigNumberish,
    referrer: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openPositionWithReferrer(
    amountIn: BigNumberish,
    leverageFactor: BigNumberish,
    amountOutMin: BigNumberish,
    lendable: string,
    tradable: string,
    trader: string,
    deadline: BigNumberish,
    referrer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openProxyPosition(
    amountIn: BigNumberish,
    leverageFactor: BigNumberish,
    amountOutMin: BigNumberish,
    lendable: string,
    proxyLendable: string,
    tradable: string,
    trader: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openProxyPositionETH(
    leverageFactor: BigNumberish,
    amountOutMin: BigNumberish,
    proxyLendable: string,
    tradable: string,
    trader: string,
    deadline: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openProxyPositionETHWithReferrer(
    leverageFactor: BigNumberish,
    amountOutMin: BigNumberish,
    proxyLendable: string,
    tradable: string,
    trader: string,
    deadline: BigNumberish,
    referrer: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openProxyPositionWithReferrer(
    amountIn: BigNumberish,
    leverageFactor: BigNumberish,
    amountOutMin: BigNumberish,
    lendable: string,
    proxyLendable: string,
    tradable: string,
    trader: string,
    deadline: BigNumberish,
    referrer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openProxyShortPosition(
    amountIn: BigNumberish,
    leverageFactor: BigNumberish,
    amountOutMin: BigNumberish,
    lendable: string,
    proxyLendable: string,
    shortable: string,
    trader: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openProxyShortPositionWithReferrer(
    amountIn: BigNumberish,
    leverageFactor: BigNumberish,
    amountOutMin: BigNumberish,
    lendable: string,
    proxyLendable: string,
    shortable: string,
    trader: string,
    deadline: BigNumberish,
    referrer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openShortPosition(
    amountIn: BigNumberish,
    leverageFactor: BigNumberish,
    amountOutMin: BigNumberish,
    lendable: string,
    shortable: string,
    trader: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openShortPositionWithReferrer(
    amountIn: BigNumberish,
    leverageFactor: BigNumberish,
    amountOutMin: BigNumberish,
    lendable: string,
    shortable: string,
    trader: string,
    deadline: BigNumberish,
    referrer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pairFactory(overrides?: CallOverrides): Promise<string>;

  reserveFactory(overrides?: CallOverrides): Promise<string>;

  stake(
    token: string,
    amount: BigNumberish,
    period: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapFactory(overrides?: CallOverrides): Promise<string>;

  swapRouter(overrides?: CallOverrides): Promise<string>;

  sweepReserveFee(
    lendable: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sweepShortingReserveFee(
    shortable: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unstake(
    token: string,
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    lendable: string,
    amount: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawETH(
    amount: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawShortable(
    shortable: string,
    amount: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    REVISION(overrides?: CallOverrides): Promise<BigNumber>;

    WETH(overrides?: CallOverrides): Promise<string>;

    calculateBalance(
      lendable: string,
      tradable: string,
      trader: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        amountOut: BigNumber;
        profit: BigNumber;
        debtPayable: BigNumber;
        protocolFee: BigNumber;
      }
    >;

    calculateOpenPosition(
      lendable: string,
      tradable: string,
      amount: BigNumberish,
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        maxAmountIn: BigNumber;
        borrowAmount: BigNumber;
        borrowRate: BigNumber;
        liquidationCost: BigNumber;
      }
    >;

    calculateOpenProxyPosition(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      amount: BigNumberish,
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        maxAmountIn: BigNumber;
        borrowAmount: BigNumber;
        borrowRate: BigNumber;
        liquidationCost: BigNumber;
      }
    >;

    calculateOpenProxyShortPosition(
      lendable: string,
      proxyLendable: string,
      shortable: string,
      amount: BigNumberish,
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        maxAmountIn: BigNumber;
        borrowAmount: BigNumber;
        borrowRate: BigNumber;
        liquidationCost: BigNumber;
      }
    >;

    calculateOpenShortPosition(
      lendable: string,
      shortable: string,
      amount: BigNumberish,
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        maxAmountIn: BigNumber;
        borrowAmount: BigNumber;
        borrowRate: BigNumber;
        liquidationCost: BigNumber;
      }
    >;

    calculateProxyBalance(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        amountOut: BigNumber;
        profit: BigNumber;
        debtPayable: BigNumber;
        protocolFee: BigNumber;
      }
    >;

    calculateProxyShortBalance(
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        amountOut: BigNumber;
        profit: BigNumber;
        debtPayable: BigNumber;
        protocolFee: BigNumber;
      }
    >;

    calculateShortBalance(
      lendable: string,
      shortable: string,
      trader: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        amountOut: BigNumber;
        profit: BigNumber;
        debtPayable: BigNumber;
        protocolFee: BigNumber;
      }
    >;

    closePosition(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    closePositionETH(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    closePositionETHWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    closePositionWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    closeProxyPosition(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    closeProxyPositionETH(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    closeProxyPositionETHWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    closeProxyPositionWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    closeProxyShortPosition(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    closeProxyShortPositionWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    closeShortPosition(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    closeShortPositionWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      lendable: string,
      amount: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    depositETH(to: string, overrides?: CallOverrides): Promise<void>;

    depositShortable(
      shortable: string,
      amount: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    fill(
      lendable: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getPosition(
      trader: string,
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        amount: BigNumber;
        value: BigNumber;
        selfValue: BigNumber;
        principalDebt: BigNumber;
        currentDebt: BigNumber;
        rate: BigNumber;
        currentCost: BigNumber;
        liquidationCost: BigNumber;
      }
    >;

    getProxyPosition(
      trader: string,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        amount: BigNumber;
        value: BigNumber;
        selfValue: BigNumber;
        principalDebt: BigNumber;
        currentDebt: BigNumber;
        rate: BigNumber;
        currentCost: BigNumber;
        liquidationCost: BigNumber;
      }
    >;

    getProxyShortPosition(
      trader: string,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        amount: BigNumber;
        value: BigNumber;
        selfValue: BigNumber;
        principalDebt: BigNumber;
        currentDebt: BigNumber;
        rate: BigNumber;
        currentCost: BigNumber;
        liquidationCost: BigNumber;
      }
    >;

    getShortPosition(
      trader: string,
      lendable: string,
      shortable: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        amount: BigNumber;
        value: BigNumber;
        selfValue: BigNumber;
        principalDebt: BigNumber;
        currentDebt: BigNumber;
        rate: BigNumber;
        currentCost: BigNumber;
        liquidationCost: BigNumber;
      }
    >;

    incentivize(
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    initialize(
      _reserveFactory: string,
      _pairFactory: string,
      _swapRouter: string,
      _WETH: string,
      _xWOW: string,
      _referralProgram: string,
      overrides?: CallOverrides
    ): Promise<void>;

    openPosition(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    openPositionETH(
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    openPositionETHWithReferrer(
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    openPositionWithReferrer(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    openProxyPosition(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    openProxyPositionETH(
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    openProxyPositionETHWithReferrer(
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    openProxyPositionWithReferrer(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    openProxyShortPosition(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    openProxyShortPositionWithReferrer(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    openShortPosition(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    openShortPositionWithReferrer(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pairFactory(overrides?: CallOverrides): Promise<string>;

    reserveFactory(overrides?: CallOverrides): Promise<string>;

    stake(
      token: string,
      amount: BigNumberish,
      period: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    swapFactory(overrides?: CallOverrides): Promise<string>;

    swapRouter(overrides?: CallOverrides): Promise<string>;

    sweepReserveFee(lendable: string, overrides?: CallOverrides): Promise<void>;

    sweepShortingReserveFee(
      shortable: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unstake(
      token: string,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      lendable: string,
      amount: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawETH(
      amount: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawShortable(
      shortable: string,
      amount: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    REVISION(overrides?: CallOverrides): Promise<BigNumber>;

    WETH(overrides?: CallOverrides): Promise<BigNumber>;

    calculateBalance(
      lendable: string,
      tradable: string,
      trader: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateOpenPosition(
      lendable: string,
      tradable: string,
      amount: BigNumberish,
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateOpenProxyPosition(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      amount: BigNumberish,
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateOpenProxyShortPosition(
      lendable: string,
      proxyLendable: string,
      shortable: string,
      amount: BigNumberish,
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateOpenShortPosition(
      lendable: string,
      shortable: string,
      amount: BigNumberish,
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateProxyBalance(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateProxyShortBalance(
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateShortBalance(
      lendable: string,
      shortable: string,
      trader: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    closePosition(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    closePositionETH(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    closePositionETHWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    closePositionWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    closeProxyPosition(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    closeProxyPositionETH(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    closeProxyPositionETHWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    closeProxyPositionWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    closeProxyShortPosition(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    closeProxyShortPositionWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    closeShortPosition(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    closeShortPositionWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deposit(
      lendable: string,
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositETH(
      to: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositShortable(
      shortable: string,
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    fill(
      lendable: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getPosition(
      trader: string,
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProxyPosition(
      trader: string,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProxyShortPosition(
      trader: string,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getShortPosition(
      trader: string,
      lendable: string,
      shortable: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    incentivize(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialize(
      _reserveFactory: string,
      _pairFactory: string,
      _swapRouter: string,
      _WETH: string,
      _xWOW: string,
      _referralProgram: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openPosition(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openPositionETH(
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openPositionETHWithReferrer(
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openPositionWithReferrer(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openProxyPosition(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openProxyPositionETH(
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openProxyPositionETHWithReferrer(
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openProxyPositionWithReferrer(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openProxyShortPosition(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openProxyShortPositionWithReferrer(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openShortPosition(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openShortPositionWithReferrer(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pairFactory(overrides?: CallOverrides): Promise<BigNumber>;

    reserveFactory(overrides?: CallOverrides): Promise<BigNumber>;

    stake(
      token: string,
      amount: BigNumberish,
      period: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapFactory(overrides?: CallOverrides): Promise<BigNumber>;

    swapRouter(overrides?: CallOverrides): Promise<BigNumber>;

    sweepReserveFee(
      lendable: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sweepShortingReserveFee(
      shortable: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unstake(
      token: string,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      lendable: string,
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawETH(
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawShortable(
      shortable: string,
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    REVISION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    calculateBalance(
      lendable: string,
      tradable: string,
      trader: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateOpenPosition(
      lendable: string,
      tradable: string,
      amount: BigNumberish,
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateOpenProxyPosition(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      amount: BigNumberish,
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateOpenProxyShortPosition(
      lendable: string,
      proxyLendable: string,
      shortable: string,
      amount: BigNumberish,
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateOpenShortPosition(
      lendable: string,
      shortable: string,
      amount: BigNumberish,
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateProxyBalance(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateProxyShortBalance(
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateShortBalance(
      lendable: string,
      shortable: string,
      trader: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    closePosition(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    closePositionETH(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    closePositionETHWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    closePositionWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    closeProxyPosition(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    closeProxyPositionETH(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    closeProxyPositionETHWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    closeProxyPositionWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    closeProxyShortPosition(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    closeProxyShortPositionWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    closeShortPosition(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    closeShortPositionWithReferrer(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deposit(
      lendable: string,
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositETH(
      to: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositShortable(
      shortable: string,
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    fill(
      lendable: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getPosition(
      trader: string,
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProxyPosition(
      trader: string,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProxyShortPosition(
      trader: string,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getShortPosition(
      trader: string,
      lendable: string,
      shortable: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    incentivize(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      _reserveFactory: string,
      _pairFactory: string,
      _swapRouter: string,
      _WETH: string,
      _xWOW: string,
      _referralProgram: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openPosition(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openPositionETH(
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openPositionETHWithReferrer(
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openPositionWithReferrer(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openProxyPosition(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openProxyPositionETH(
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openProxyPositionETHWithReferrer(
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openProxyPositionWithReferrer(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      tradable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openProxyShortPosition(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openProxyShortPositionWithReferrer(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      proxyLendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openShortPosition(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openShortPositionWithReferrer(
      amountIn: BigNumberish,
      leverageFactor: BigNumberish,
      amountOutMin: BigNumberish,
      lendable: string,
      shortable: string,
      trader: string,
      deadline: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pairFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    reserveFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    stake(
      token: string,
      amount: BigNumberish,
      period: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sweepReserveFee(
      lendable: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sweepShortingReserveFee(
      shortable: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unstake(
      token: string,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      lendable: string,
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawETH(
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawShortable(
      shortable: string,
      amount: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
