/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ParamProviderStateV1,
  ParamProviderStateV1Interface,
} from "../ParamProviderStateV1";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ParamProviderStateV1__factory {
  static readonly abi = _abi;
  static createInterface(): ParamProviderStateV1Interface {
    return new utils.Interface(_abi) as ParamProviderStateV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ParamProviderStateV1 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ParamProviderStateV1;
  }
}
